<?php
	$_set_id = $this->getPhotosetId();
	$_set_name = $this->getPhotoSetNameFromID($_set_id);
	$_page = $this->getPageNumber();
	$hasTooltip = $this->carouselHasTooltip();
?>
<div class="flickr_gallery">

	<?php
		$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		$breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		$breadcrumbs->addCrumb('gallery', array('label'=>'Gallery', 'title'=>'Gallery', 'link'=>Mage::getUrl('gallery')));
		$breadcrumbs->addCrumb('set', array('label'=>$_set_name, 'title'=>$_set_name));
		echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
	?>
    
	<div class="page-title">
		<h1><?php echo $_set_name; ?></h1>
	</div>
	
	<div id="flickr_galley_ajax">
		<div id="loading-mask">
			<img src="<?php echo $this->getSkinUrl('inchoo/flickrgallery/images/loading.gif') ?>" alt="<?php echo Mage::helper('flickr')->__('Loading...') ?>"/>
			<?php echo Mage::helper('flickr')->__('Please wait...') ?>
		</div>
	</div>

	<?php if($hasTooltip): ?>
		<style type="text/css">
			@import url("<?php echo $this->getSkinUrl('inchoo/flickrgallery/enyo-opentip/opentip.css') ?>");
			@import url("<?php echo $this->getSkinUrl('inchoo/flickrgallery/css/tooltips.css') ?>");
		</style>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('inchoo/flickrgallery/enyo-opentip/opentip.js') ?>"></script>
	<?php endif; ?>
	<script type="text/javascript">
	//<![CDATA[
		document.observe("dom:loaded", function(){
			new Ajax.Request("<?php echo Mage::getUrl('gallery/index/renderset/') . "id/$_set_id/page/$_page" ?>",{
				method:'get',
				onSuccess: function (data){
					var response = data.responseText;
					$('flickr_galley_ajax').innerHTML = response;
					
					<?php if($hasTooltip): ?>
					$$('.opentip').each(function(elem){
						var content = elem.readAttribute('title');
						elem.removeAttribute('title');
						$(elem.readAttribute('id')).addTip(
							content, 
							{
								<?php $_tooltip_style = $this->carouselGetTooltipStyle(); ?>
								<?php if($_tooltip_style): ?>
									className: '<?php echo $_tooltip_style; ?>',
								<?php endif; ?>
								delay: 0.1,
								stem: false,
								target: false,
								tipJoint: ['center', 'top']
							});
					});
					<?php endif; ?>
				}
			});
		});
	//]]>
	</script>

</div>